nome = str(input('Digite seu nome: ')).strip()
print('Analisando o seu nome...')
print('Seu nome em maiúsculas é {}' .format(nome.upper()))
print('Seu nome em minúsculas é {}' .format(nome.lower()))
print('Seu nome ao todo {} letras' .format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {}' .format((nome.find (' ')))
